### ISSUE TITLE
help to replicate tetme

### ISSUE THREAD

**Issue by otaolafranc** [cgg-bern/hex-me-if-you-can#1]
Hello,
I am looking to use AlgoHex and post it a message about its use (https://github.com/cgg-bern/AlgoHex/issues/7#issuecomment-2563598259) I know that AlgoHex uses as input the vtk format of a tet mesh generated using tetme.py https://github.com/cgg-bern/hex-me-if-you-can/blob/main/scripts/tetme.py but I am not sure of the meshing parameters, I want to recreate this part of the pipeline in salome instead of gmsh. it has as gmsh algorithms embebed and also some others. I see that it makes the different groups for vertexes, edges, surfaces and volume of the geometry but what I am looking for is the algorithm parameters, such as min max size, etc. as I can not see this in the tetme.py
thanks in advance

**Comment by pa-beaufort** [comment]
Hello. The parameters are defined in the meta data files, for instance
https://github.com/cgg-bern/hex-me-if-you-can/blob/main/meta/s01c_cube.yaml

Check out section 4, paragraph "How to contribute"
https://www.algohex.eu/publications/hex-me-if-you-can/hexmeifyoucan.pdf

**Comment by otaolafranc** [comment]
thank you for your kind answer, my main doubt is which would be the best input mesh? as I see that there are 3 types, C/U/B from experience i generally tent to use U meshes (I would even do for the B case, a BU the bounding box but with uniform size elements) I would love to have your input in this regards. also if the tet mesh impacts too much (or almost non when the quality is already acceptable....) to the output mesh quality/ success in getting an hex mesh

**Comment by pa-beaufort** [comment]
Ok - if I understand you correctly - you aim here to provide a tet mesh good enough for hexaedrization (using AlgoHex).
However, HexMe is a dataset to test/assess hex meshers, meaning it has to provide the three types of meshes (c|u|b) for a CAD model.

**Comment by otaolafranc** [comment]
I would say that you understood me correctly :). I want to use algoHex and get the best possible results (and prepare the best input possible to make it succed) and as algoHex uses the workflow of Hex-me-if-you-can I wanted to recreate it in salome. I could share the scripts for Hex-me-if-you-can if it something that could be interesting for you.... I dont have the same level of programming as the person who did the scripts (I imagine that it is you) but they are at least functional.

**Comment by pa-beaufort** [comment]
Ok, thanks for your interest.

AlgoHex and HexMe are not related, except that AlgoHex uses HexMe policy for feature tag.
The end of section 3 explains this policy
> Gmsh [GR09] does not only mesh the volume, [...]
> 4. CELL_DATA: integer corresponding to the element tag that belongs to the CAD feature.
![image](https://github.com/user-attachments/assets/ab7dc1b4-b69b-4709-9d31-588bb15dc070)

I never use Salome. With Gmsh, you achieve this by defining `Physical Groups` for each `Geometrical Entity`.
 Lines https://github.com/cgg-bern/hex-me-if-you-can/blob/8f00f02579037cc893042f2ee2c910b20e3fb1b0/scripts/tetme.py#L61C1-L76C17 perform this using Gmsh API. Then , you export the generated mesh with ` .vtk` extension
```
gmsh.write("filename.vtk")
```

My advice is that you should NOT use HexMe workflow to generate meshes for AlgoHex, since you only need some meshes for some FEA.
One more time, HexMe is only an evaluation tool for hex meshers - not a way to feed AlgoHex.

Don't hesitate to reach out for advice related to AlgoHex use and best practice on AlgoHex github :-)
